Common/header changes to files in dir/styling/rwd
adrianSACHA/movies-browser pull request #36
Opened 2023-02-08 11:38 UTC by adrianSACHA

fixed active navigation and RWD.
Please review :)

2023-02-08 11:41 UTC, Rudolfini commented on src/common/Navigation/Search/styled.js
> +    /* gap: 8px; */
is this commented line necessary?

2023-02-08 11:42 UTC, Rudolfini commented on src/common/Navigation/styled.js
> +
empty line

2023-02-08 11:43 UTC, Rudolfini commented on src/common/Navigation/styled.js
> +    /* gap: 5px; */
should you keep it or remove?

2023-02-08 11:45 UTC, Rudolfini requested changes
Good job Adrian! 
Theres a few comments here, I think if those lines are not necessary you should delete them.

2023-02-09 08:16 UTC, adrianSACHA commented on src/common/Navigation/Search/styled.js
> +    /* gap: 8px; */
fixed :)

2023-02-09 08:17 UTC, adrianSACHA commented on src/common/Navigation/styled.js
> +
fixed

2023-02-09 08:17 UTC, adrianSACHA commented on src/common/Navigation/styled.js
> +    /* gap: 5px; */
changed it

2023-02-09 08:21 UTC, adrianSACHA commented
Changed styles,
added breakpoint for responsiveness.

Please review it ;)

2023-02-09 10:27 UTC, konradkapica approved these changes
Great!

2023-02-09 10:27 UTC, merged